language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
matrix:
  allow_failures:
    - python: pypy
  fast_finish: true
# command to install dependencies
install:
  - "pip install . --use-mirrors"
# command to run tests
script: python setup.py test
